server:
  port: 8764
  
spring:
  application:
    name: farm-monitor
  security:
    user:
      name: "admin"
      password: "admin"
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: turbine
      client:
        url: http://localhost:8764
        instance:
          service-base-url: http://localhost:8764  
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: "admin"
      user.password: "admin"
    
#    statusPageUrlPath: /actuator/info
#    healthCheckUrlPath: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
#    healthcheck: true
#    registerWithEureka: true
#    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/ 
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS